name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:


jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
          name: Check out code
      
        - uses: mr-smithers-excellent/docker-build-push@v3
          name: Build & push Docker image
          with:
            image: gagandeep39/helloworld
            tag: latest
            registry: registry-url.io
            dockerfile: Dockerfile
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}