name: Docker

on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
    push:
        steps:
            uses: docker/build-push-action@v1
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                repository: myorg/myrepository
                tags: latest