name: Docker

on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
    push:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
            name: Check out code
          - uses: docker/build-push-action@v1
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                repository: gagandeep39/helloworld
                tags: latest
